echo "" >> ./.env
echo "RAILS_PRODUCTION_KEY=$RAILS_PRODUCTION_KEY" >> ./.env
echo "MAILER_ADDRESS=$MAILER_ADDRESS" >> ./.env
echo "MAILER_DOMAIN=$MAILER_DOMAIN" >> ./.env
echo "MAILER_PASSWORD=$MAILER_PASSWORD" >> ./.env
echo "MAILER_USER=$MAILER_USER" >> ./.env
