version: '3'
services:

  postgres:
    image: registry.gitlab.com/basemate-ops/workflow/postgres
    expose:
      - 5432
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "production"
    env_file:
      - ./.env

  rails:
    image: registry.gitlab.com/basemate-ops/neworld:latest
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    environment:
      RAILS_ENV: "production"
      POSTGRES_DB: "production"
    env_file:
      - ./.env
    volumes:
      - storage-volume:/app/storage
    command: "rails server --binding 0.0.0.0 --port 3000"

  redis:
    image: redis:5.0.7-alpine
    volumes:
      - redis-volume:/data

volumes:
  redis-volume:
  data-volume:
  storage-volume:
